version: 1
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: app.log
    encoding: utf-8
    mode: w
  console:
    class: logging.StreamHandler
    level: CRITICAL
    formatter: default
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file, console]